name: CI Action

on:
  pull_request:
    branches:
      - main

jobs:
  ci-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Test dot file
        id: ci-dot-file
        uses: ./
        with:
          dot-file-path: ./test_fixtures/graph.dot
          output-format: markdown
      - name: Test TF dir
        id: ci-tf-dir
        uses: ./
        with:
          terraform-dir-path: ./test_fixtures/terraform
          output-format: markdown
      - name: Test State file
        id: ci-state-file
        uses: ./
        with:
          terraform-state-path: ./test_fixtures/state.json
          output-format: markdown
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@632cf9ce90574d125be56b5f3405cda41a84e2fd # v2.3.1
        with:
          message: |
            #### Below is a list of the action run against all the test fixtures
            <details>
              <summary>Dot file test</summary>

              ${{ steps.ci-dot-file.outputs.categorized-resources }}
            </details>

            <details>
              <summary>Terraform directory test</summary>

              ${{ steps.ci-tf-dir.outputs.categorized-resources }}
            </details>

            <details>
              <summary>Terraform state test</summary>

              ${{ steps.ci-state-file.outputs.categorized-resources }}
            </details>
          comment_tag: summary-comment
          mode: recreate
